In [1]:
# demoNumpy.py
import numpy as np 

data = [1,2,3]
arr = np.array(data)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
result = arr * 10 
result 

array([10, 20, 30])

In [4]:
#2차원 배열
data2d = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(data2d[1])

[4, 5, 6]


In [6]:
arr = np.array(data2d)
#변수[행,열]
arr[:, 1]


array([2, 5, 8])

In [8]:
data2 = [
    [1,2],
    [3,4]
]

arr2 = np.array(data2)
print(arr2)
print(type(arr2))
print(type(arr2[0]))
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(2, 2)
2
int32


In [9]:
data = [
    [1],
    [2],
    [3],
    [4]
]
c = np.array(data)
c.shape 

(4, 1)

In [10]:
print( np.zeros(3) )
print( np.ones(3) )


[0. 0. 0.]
[1. 1. 1.]


In [11]:
size = (3,4)
print(np.zeros(size))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
print( np.arange(5) )
print( np.arange(1,5) )
print( np.arange(0.0, 5.0, 0.2) )


[0 1 2 3 4]
[1 2 3 4]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]


In [13]:
ndarr1 = np.arange(6)
ndarr2 = ndarr1.reshape(2,3)
ndarr2 

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
arr = np.arange(4).reshape(2,2)
print(arr)
print(arr[0])
print(arr[1])

[[0 1]
 [2 3]]
[0 1]
[2 3]


In [18]:
#시간 측정(속도가 빠르다)
a = np.arange(10000).reshape(100,100)
%timeit a[0,50]

133 ns ± 12 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [19]:
#시간 측정(속도가 느리다)
a = np.arange(10000).reshape(100,100)
%timeit a[0][50]

389 ns ± 125 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
arr[1:4, 2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [22]:
arr[1:, 2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [23]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a + b)
print(a * b)

[3 5 7]
[ 2  6 12]


In [24]:
a + 3 

array([4, 5, 6])

In [26]:
print("---고가와 저가---") 
high = [92700, 92400, 92100, 94300, 92300]
low = [90000, 91100, 91700, 92100, 90900]

arr_high = np.array(high)
arr_low = np.array(low)
arr_diff = arr_high - arr_low 
arr_diff 

---고가와 저가---


array([2700, 1300,  400, 2200, 1400])

In [27]:
#조건이 있는 경우
arr = np.array([10,20,30])
print(arr > 10)

[False  True  True]


In [28]:
cond = arr > 10 
print( arr[cond] )

[20 30]


In [29]:
print( cond.all() )
print( cond.any() )

False
True


In [30]:
arr = np.array([10,20,30])
cond0 = arr > 10 
cond1 = arr < 30 
print( arr[cond0 & cond1] )

[20]


In [31]:
arr = np.where(arr>10, 1, 0)
arr 

array([0, 1, 1])

In [32]:
arr = np.array([10,20,30])
arr = np.where(arr>10, arr+10, arr-10)
arr 

array([ 0, 30, 40])

In [33]:
arr = np.arange(8).reshape(4,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [34]:
arr.sum() 

28

In [35]:
print( arr.sum(axis=0) )
print( arr.sum(axis=1) )

[12 16]
[ 1  5  9 13]
